apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-ceph-data
  namespace: default
  labels:
    app: redis
    release: redis
    role: master
    storage: ceph
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
